apiVersion: v1
kind: Namespace
metadata:
  name: daily-hadith
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: daily-hadith-config
  namespace: daily-hadith
data:
  backend-url: "http://daily-hadith-backend:8000"
  