apiVersion: apps/v1
kind: Deployment
metadata:
  name: daily-hadith-backend
  namespace: daily-hadith
spec:
  replicas: 2
  selector:
    matchLabels:
      app: daily-hadith-backend
  template:
    metadata:
      labels:
        app: daily-hadith-backend
    spec:
      containers:
      - name: daily-hadith-backend
        image: sheikhnashid/daily-hadith-app:v8
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: daily-hadith-backend
  namespace: daily-hadith
spec:
  selector:
    app: daily-hadith-backend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
  type: NodePort